exports.constants = {
    phoneNoRegex: /^\+?\d+$/,   // First character is optional +, and other is digit
    nameRegex: /^[a-zA-Z\s]+$/,  // Alphabet and space only
    alphabetRegex: /^[a-zA-Z]*$/,  // Alphabet only
    numberRegex: /^\d+$/,       // Digit only
    searchPattern: /^[a-zA-Z0-9 ]*$/,  // Alphabet, digit and space only
    emailRegex: /^[\w-]+(\.[\w-]+)*@([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$/,    // Email validation
    foodPreferencesRegex: /^[a-zA-Z0-9()\- ]+$/,  // Alphabet, digit, space and ()- only
    dateRegex: /^\d{1,2} (Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) \d{4}$/,   // format like this = "12 Mar 2024"
    dateMonthYearRegex: /^\d{4}-\d{2}-\d{2}$/,  // format like this = "2024-03-12"
    passwordRegex: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+])[A-Za-z\d!@#$%^&*()_+]{8,24}$/, // minimum 1 lowerCase, upperCase, specialCharacter, number and minimum lenght 8 and maximum lenght 25
    ratingRegex: /^(?!.*[a-zA-Z])^(?:0|[1-4](?:\.\d{1,2})?|5(?:\.0{1,2})?)$/

}

exports.disposableEmailProviders = [
    "yopmail.com",
    "temp-mail.org",
    "guerrillamail.com",
    "mailinator.com",
    "10minutemail.com",
    "dispostable.com",
    "maildrop.cc",
    "sharklasers.com",
    "getnada.com",
    "throwawaymail.com",
    "tempmailgen.com",
    "mintemail.com",
    "temp-mail.io",
    "trashmail.com",
    "burnermail.io",
    "moakt.com",
    "mytemp.email",
    "inboxalias.com",
    "mailnesia.com",
    "notsharingmy.info",
    "spamgourmet.com",
    "guerrillamail.net",
    "mailcatch.com",
    "anonbox.net",
    "mailforspam.com",
    "mailmoat.com",
    "spam4.me",
    "spambog.com",
    "spambox.us",
    "spamcowboy.com",
    "spamherelots.com",
    "spambob.net",
    "spam.su",
    "spamthis.co.uk",
    "tempmailaddress.com",
    "throwawaymail.org",
    "hidemyass.com",
    "fakeinbox.com",
    "mailinator2.com",
    "mvrht.com",
    "spamgourmet.net",
    "zeta-telecom.com",
    "trashmail.ws",
    "cool.fr.nf",
    "2prong.com",
    "spam.su",
    "spammotel.com",
    "spambob.org",
    "spambob.com",
    "mailcatch.com",
    "spambox.org",
    "fake-mail.net",
    "33mail.com",
    "spambob.biz",
    "mintemail.com",
    "spam.la",
    "mailinator.net",
    "spambog.ru",
    "mailinater.com",
    "throwawaymail.com",
    "spamgourmet.org",
    "jetable.org",
    "e4ward.com",
    "mailinator2.com",
    "bouncr.com",
    "mailnull.com",
    "spammotel.com",
    "spamgourmet.net",
    "mailmetrash.com",
    "dispostable.com",
    "maildrop.cc",
    "throwawaymail.org",
    "tempmail.net",
    "throwawaymail.org",
    "armyspy.com",
    "mailnesia.com",
    "trashmail.com",
    "spamspot.com",
    "mytrashmail.com",
    "trashmail.me",
    "spambox.com",
    "spambox.in",
    "spambox.info",
    "spambox.me",
    "spambox.net",
    "spambox.org",
    "spambox.pw",
    "spambox.review",
    "spambox.site",
    "spambox.space",
    "spambox.stream",
    "spambox.trade",
    "spambox.us",
    "spambox.website",
    "spambox.win",
    "spambox.xyz",
    "tempmailer.com"
];